# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

create_P_compact_cpp <- function(p, q) {
    .Call(`_WH_create_P_compact_cpp`, p, q)
}

backsolve_compact_cpp <- function(C, b, transpose = FALSE) {
    .Call(`_WH_backsolve_compact_cpp`, C, b, transpose)
}

diag_V_compact_cpp <- function(C) {
    .Call(`_WH_diag_V_compact_cpp`, C)
}

get_prod_P_y_compact_cpp <- function(y, C_list) {
    .Call(`_WH_get_prod_P_y_compact_cpp`, y, C_list)
}

get_prod_P_K_compact_cpp <- function(K, C_list) {
    .Call(`_WH_get_prod_P_K_compact_cpp`, K, C_list)
}

submatrix_compact_cpp <- function(C, drop_indices) {
    .Call(`_WH_submatrix_compact_cpp`, C, drop_indices)
}

cholesky_compact_lapack <- function(C, inplace = FALSE) {
    .Call(`_WH_cholesky_compact_lapack`, C, inplace)
}

invert_cholesky_compact_lapack <- function(C, transpose = FALSE) {
    .Call(`_WH_invert_cholesky_compact_lapack`, C, transpose)
}

backsolve_mat_compact_lapack <- function(C, B, transpose = FALSE) {
    .Call(`_WH_backsolve_mat_compact_lapack`, C, B, transpose)
}

eigenvalues_compact_lapack <- function(C) {
    .Call(`_WH_eigenvalues_compact_lapack`, C)
}

